// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg7SWKYUF17bjS2QjIezkKswn7eXoUtQw',
    appId: '1:588930715186:web:c551ac60d326b71387f62b',
    messagingSenderId: '588930715186',
    projectId: 'taskweb-30a13',
    authDomain: 'taskweb-30a13.firebaseapp.com',
    storageBucket: 'taskweb-30a13.firebasestorage.app',
    measurementId: 'G-D2ZQSNBH6E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAUPV1b8dFqRct83yctstpNHn5p8ka5XDk',
    appId: '1:588930715186:android:e1b2523188e81dff87f62b',
    messagingSenderId: '588930715186',
    projectId: 'taskweb-30a13',
    storageBucket: 'taskweb-30a13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqszrd4rhPl-yADxQC_V99U6BO7wLJ6_8',
    appId: '1:588930715186:ios:785fed1a999bc6bc87f62b',
    messagingSenderId: '588930715186',
    projectId: 'taskweb-30a13',
    storageBucket: 'taskweb-30a13.firebasestorage.app',
    iosBundleId: 'com.abdalluh.flutterWebTask',
  );
}
